name: ci/cd
on: push
jobs:
  test:
    runs-on: unbuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: installing node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Build Project
        run: npm run build
