name: ci/cd
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
            - name: Formate by prettier app
              run: npm run prettier
            - name: Lint app
              run: npm run lint

    cd:
        name: cd
        needs: ci
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
            - name: Build app
              run: npm run build
